const SCHOOLS = [
  {
    id: "tum",
    logo: "/assets/schools/tum.png",
    rank: "#1",
    name: "慕尼黑工业大学",
    englishName: "Technical University of Munich",
    germanName: "Technische Universität München",
    city: "Munich / Garching / Freising",
    state: "Bayern",
    type: "TU9 工科强校，综合型技术大学",
    website: "https://www.tum.de/en/studies/degree-programs",
    summary: "德国最具代表性的技术大学之一，工程、计算机、自然科学、管理交叉方向都非常强，申请竞争激烈，材料审核通常较细。",
    strengths: ["机械、汽车、航空航天、电子信息、计算机、数据科学", "工程管理、金融信息管理、可持续与能源方向", "项目页面、模块手册、语言要求和 aptitude assessment 需要逐项核对"],
    programs: ["Data Engineering and Analytics", "Aerospace", "Automotive Engineering", "Electrical Engineering and Information Technology", "Finance and Information Management"],
    fitFor: ["成绩较强", "课程匹配度高", "有项目/科研/实习证明", "目标明确的工科或数据方向"],
    application: "多数学位项目通过 TUMonline 申请，不同项目有独立截止日期、能力评估和材料清单。",
    language: "英语、德语或英德混合项目都有；要按具体项目确认 IELTS/TOEFL/TestDaF/DSH 要求。",
    materialTips: ["成绩单课程与模块匹配很重要", "动机信要写清目标方向和 TUM 项目模块", "部分项目需要额外 essay、aptitude 文件或推荐材料"]
  },
  {
    id: "tu-berlin",
    logo: "/assets/schools/tu-berlin.png",
    rank: "#2",
    name: "柏林工业大学",
    englishName: "TU Berlin",
    germanName: "Technische Universität Berlin",
    city: "Berlin",
    state: "Berlin",
    type: "TU9 工科大学，城市区位强",
    website: "https://www.tu.berlin/en/studying/study-programs",
    summary: "位于柏林，计算机、信息系统、工程、城市、环境和可持续方向选择多，适合想结合大城市实习资源的学生。",
    strengths: ["计算机、信息系统、汽车系统、土木、建筑能源", "城市规划、环境、可持续与经济交叉方向", "柏林实习和创业资源丰富"],
    programs: ["Computer Science", "Information Systems Management", "Automotive Systems", "Civil Engineering", "Building Energy Engineering"],
    fitFor: ["想去柏林", "工科和信息方向", "看重城市资源", "可接受德语项目核验"],
    application: "项目申请要求差异较大，部分项目通过 uni-assist 或学校系统处理，需按项目页确认。",
    language: "德语项目较多，也有英语或英德混合方向；语言证书要尽早准备。",
    materialTips: ["确认是否需要 APS 和 VPD/uni-assist", "课程核对信息要突出数学、工程基础和编程能力", "跨专业申请要重点解释先修课"]
  },
  {
    id: "kit",
    logo: "/assets/schools/kit.png",
    rank: "#3",
    name: "卡尔斯鲁厄理工学院",
    englishName: "Karlsruhe Institute of Technology",
    germanName: "Karlsruher Institut für Technologie",
    city: "Karlsruhe",
    state: "Baden-Württemberg",
    type: "TU9，工程与自然科学强校",
    website: "https://www.sle.kit.edu/english/vorstudium/degree-programs.php",
    summary: "KIT 工程、计算机、电气、机械、材料、化工和数字经济方向突出，适合课程基础扎实的工科学生。",
    strengths: ["机械、电气、计算机、材料、化工", "数字经济、遥感、地理信息和能源方向", "研究导向明显，课程深度较高"],
    programs: ["Electrical Engineering and Information Technology", "Chemical and Process Engineering", "Industrial Engineering and Management", "Remote Sensing and Geoinformatics", "Digital Economics"],
    fitFor: ["工科基础扎实", "数学和工程课程完整", "希望走研究或工业路线"],
    application: "多数项目需通过学校申请系统提交，部分项目有具体先修课和成绩要求。",
    language: "德语项目比例较高，英语项目需逐项确认。",
    materialTips: ["先修课核验很关键", "课程核对信息建议覆盖数学、工程、实验和项目", "动机信要写清研究或工业目标"]
  },
  {
    id: "uni-stuttgart",
    logo: "/assets/schools/uni-stuttgart.png",
    rank: "#4",
    name: "斯图加特大学",
    englishName: "University of Stuttgart",
    germanName: "Universität Stuttgart",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    type: "工程与应用科学强校",
    website: "https://www.student.uni-stuttgart.de/en/study-programs/",
    summary: "斯图加特地区工业基础强，机械、汽车、航天、软件、数据和工程控制方向很有代表性。",
    strengths: ["机械、汽车、航空航天、工程控制", "软件工程、AI 与数据科学", "与巴登-符腾堡工业生态关联密切"],
    programs: ["Artificial Intelligence and Data Science", "Software Engineering", "Mechanical Engineering", "Engineering Cybernetics", "Materials Science"],
    fitFor: ["机械/车辆/控制背景", "软件和数据方向", "希望连接德国工业就业"],
    application: "申请材料通常包含成绩单、语言、课程/模块信息，部分项目会核验专业匹配。",
    language: "英语项目和德语项目并存。",
    materialTips: ["项目经历要写清工程问题和工具", "控制、数学、编程课程对匹配很有帮助", "汽车邻近方向不要替代真实机器人方向"]
  },
  {
    id: "tu-darmstadt",
    logo: "/assets/schools/tu-darmstadt.png",
    rank: "#5",
    name: "达姆施塔特工业大学",
    englishName: "Technical University of Darmstadt",
    germanName: "Technische Universität Darmstadt",
    city: "Darmstadt",
    state: "Hessen",
    type: "TU9，工程与计算强校",
    website: "https://www.tu-darmstadt.de/studieren/studieninteressierte/studienangebot_studiengaenge/index.en.jsp",
    summary: "以工程、计算机、能源、计算工程和网络安全见长，适合技术基础扎实、偏工程实践和研究的学生。",
    strengths: ["计算工程、能源、机械、电气、信息安全", "工程数学和仿真建模方向强", "德国中部位置，靠近法兰克福产业圈"],
    programs: ["Computational Engineering", "Energy Science and Engineering", "Autonomous Systems", "Mechanical and Process Engineering"],
    fitFor: ["工程仿真", "能源系统", "机器人/自主系统", "信息安全"],
    application: "按项目核验学历背景、ECTS 和语言要求，部分项目可能需要详细课程信息。",
    language: "德语和英语项目都有。",
    materialTips: ["课程核对信息建议突出数学、建模、编程和实验", "项目经历可强调仿真、控制或系统设计", "申请前确认是否需要德语等级"]
  },
  {
    id: "tu-dresden",
    logo: "/assets/schools/tu-dresden.png",
    rank: "#6",
    name: "德累斯顿工业大学",
    englishName: "TU Dresden",
    germanName: "Technische Universität Dresden",
    city: "Dresden",
    state: "Sachsen",
    type: "TU9，综合型技术大学",
    website: "https://tu-dresden.de/studium/vor-dem-studium/studienangebot",
    summary: "学科覆盖较广，工程、计算、土木、材料、数据法、知识产权法等方向都有可核对项目。",
    strengths: ["土木结构、计算工程、材料、数学经济", "知识产权法、数据法等交叉项目", "生活成本相对友好"],
    programs: ["Computational Modeling and Simulation", "Advanced Computational and Civil Engineering Structural Studies", "Data Law", "Mathematics in Business and Economics"],
    fitFor: ["工程计算", "土木结构", "法律数据交叉", "预算敏感"],
    application: "项目入口和材料要求差异较大，必须逐个项目核对。",
    language: "德语、英语项目并存。",
    materialTips: ["交叉专业要解释本科课程与目标项目连接", "法律/数据方向要避免把纯工程项目误排太高", "低证据项目只作探索候选"]
  },
  {
    id: "fau",
    logo: "/assets/schools/fau.png",
    rank: "#7",
    name: "埃尔朗根-纽伦堡大学",
    englishName: "FAU Erlangen-Nürnberg",
    germanName: "Friedrich-Alexander-Universität Erlangen-Nürnberg",
    city: "Erlangen / Nürnberg",
    state: "Bayern",
    type: "综合大学，工程、商科、生命科学均衡",
    website: "https://www.fau.eu/education/degree-programmes/",
    summary: "FAU 覆盖工程、数据、能源、商科、健康管理和生命科学方向，适合希望在巴伐利亚寻找多元项目的学生。",
    strengths: ["数据科学、清洁能源、材料与过程", "Finance/FACT、健康管理、医学管理", "项目数量多，适合做中高匹配池"],
    programs: ["Data Science", "Clean Energy Processes", "Advanced Materials and Processes", "FACT", "Health Management and Health Economics"],
    fitFor: ["商科金融", "健康管理", "能源材料", "数据科学"],
    application: "项目要求差异明显，需查看各项目页面和申请期。",
    language: "英语和德语项目都有。",
    materialTips: ["商科方向要准备统计、经济、管理课程证据", "健康管理需解释医学/经济/管理背景", "能源材料方向需补足工程基础"]
  },
  {
    id: "uni-cologne",
    logo: "/assets/schools/uni-cologne.png",
    rank: "#8",
    name: "科隆大学",
    englishName: "University of Cologne",
    germanName: "Universität zu Köln",
    city: "Cologne",
    state: "Nordrhein-Westfalen",
    type: "大型综合大学，商科、经济和数据方向强",
    website: "https://portal.uni-koeln.de/en/studying/degree-programs",
    summary: "科隆大学商科、经济、金融、商业分析、计算生物等方向常见，是商科和数据交叉申请的重要参考。",
    strengths: ["Business Analytics、Finance、Accounting、Economics", "计算生物、社会科学与数据交叉", "城市资源和企业环境较好"],
    programs: ["Business Analytics & Econometrics", "Business Administration - Finance", "Accounting & Taxation", "Computational Biology"],
    fitFor: ["商科金融", "商业分析", "经济学", "数据交叉"],
    application: "商科项目竞争较高，通常看课程背景、成绩、语言和相关经历。",
    language: "英语项目较多，但具体项目需逐项确认。",
    materialTips: ["量化课程、统计、计量经济和编程是加分点", "动机信要避免只写城市吸引力", "跨专业申请需补充先修课说明"]
  },
  {
    id: "fu-berlin",
    logo: "/assets/schools/fu-berlin.png",
    rank: "#9",
    name: "柏林自由大学",
    englishName: "Freie Universität Berlin",
    germanName: "Freie Universität Berlin",
    city: "Berlin",
    state: "Berlin",
    type: "综合大学，人文社科、生命科学、计算机均衡",
    website: "https://www.fu-berlin.de/en/studium/studienangebot/",
    summary: "柏林自由大学在人文社科、文化传媒、经济、计算机、生物信息等方向都有代表项目，适合社科与数据交叉学生。",
    strengths: ["文化传媒管理、经济学、计算机、生物信息", "柏林城市资源丰富", "社科、人文和数据交叉选择多"],
    programs: ["Computer Science", "Bioinformatics", "Economics", "Culture and Media Management", "Regulatory Law"],
    fitFor: ["人文社科", "文化传媒", "生物信息", "计算机"],
    application: "部分项目可能通过 uni-assist 或学校系统，申请路径要按项目确认。",
    language: "德语和英语项目并存。",
    materialTips: ["社科方向要写清研究兴趣和方法训练", "文化传媒需解释作品/实践经历", "计算机方向要补充编程课程"]
  },
  {
    id: "uni-mannheim",
    logo: "/assets/schools/uni-mannheim.png",
    rank: "#10",
    name: "曼海姆大学",
    englishName: "University of Mannheim",
    germanName: "Universität Mannheim",
    city: "Mannheim",
    state: "Baden-Württemberg",
    type: "商科、经济和社会科学强校",
    website: "https://www.uni-mannheim.de/en/academics/programs/",
    summary: "曼海姆大学以商科、金融、经济、社会数据科学和管理方向闻名，商科申请竞争强。",
    strengths: ["金融、会计、税务、管理、经济", "Social Data Science 与量化社科", "适合商科高匹配候选"],
    programs: ["Mannheim Master in Management", "Mannheim Master in Finance", "Mannheim Master in Data Science", "Social Data Science"],
    fitFor: ["商科强背景", "金融会计", "管理咨询", "社会数据"],
    application: "商科项目通常重视课程匹配、成绩、语言和量化背景。",
    language: "英语项目较多，部分要求具体英语成绩。",
    materialTips: ["GMAT/GRE 是否有用需按项目确认", "CV 要突出量化、实习和商业分析经历", "动机信应具体到目标项目课程和职业路线"]
  },
  {
    id: "rwth-aachen",
    logo: "/assets/schools/rwth-aachen.png",
    rank: "#11",
    name: "亚琛工业大学",
    englishName: "RWTH Aachen University",
    germanName: "Rheinisch-Westfälische Technische Hochschule Aachen",
    city: "Aachen",
    state: "Nordrhein-Westfalen",
    type: "TU9，德国工科代表院校",
    website: "https://www.rwth-aachen.de/go/id/bkpx/lidx/1",
    summary: "RWTH 工程声誉强，机械、车辆、材料、电子、计算机和工业工程都是常见目标方向。",
    strengths: ["机械、汽车、材料、电气、计算机", "工业工程和生产系统", "工科申请竞争和课程核验要求较高"],
    programs: ["Automotive Engineering", "Production Systems Engineering", "Electrical Engineering", "Computer Engineering", "Materials Engineering"],
    fitFor: ["工科高匹配", "机械车辆", "工业工程", "材料制造"],
    application: "具体项目要求差异较大，需核对先修课、语言和申请系统。",
    language: "英语、德语项目都有。",
    materialTips: ["课程核对信息要精确到学分和内容", "机械车辆方向应准备项目/实习证据", "低匹配跨专业需谨慎"]
  },
  {
    id: "lmu",
    logo: "/assets/schools/lmu.png",
    rank: "#12",
    name: "慕尼黑大学",
    englishName: "LMU Munich",
    germanName: "Ludwig-Maximilians-Universität München",
    city: "Munich",
    state: "Bayern",
    type: "顶尖综合大学",
    website: "https://www.lmu.de/en/study/all-degrees-and-programs/",
    summary: "LMU 是德国顶尖综合大学之一，生命科学、数据、经济、心理、人文社科方向值得参考。",
    strengths: ["生命科学、心理、经济、数据、人文社科", "慕尼黑城市资源强", "综合大学课程广"],
    programs: ["Data Science", "Economics", "Psychology", "Neuroscience", "Biology"],
    fitFor: ["综合型背景", "生命科学", "心理社科", "经济数据"],
    application: "各学院和项目要求差异较大，需要逐项查看官网。",
    language: "德语项目较多，也有英语硕士项目。",
    materialTips: ["研究方向要具体", "生命科学/心理方向需准备方法和实验经历", "经济数据方向重视数学和统计"]
  },
  {
    id: "heidelberg",
    logo: "/assets/schools/heidelberg.png",
    rank: "#13",
    name: "海德堡大学",
    englishName: "Heidelberg University",
    germanName: "Ruprecht-Karls-Universität Heidelberg",
    city: "Heidelberg",
    state: "Baden-Württemberg",
    type: "历史悠久的研究型综合大学",
    website: "https://www.uni-heidelberg.de/en/study/all-subjects",
    summary: "海德堡大学以医学、生命科学、自然科学、人文社科和研究导向项目见长。",
    strengths: ["医学、生命科学、分子生物、物理、数据方法", "研究型氛围强", "适合科研经历较好的学生"],
    programs: ["Molecular Biosciences", "Physics", "Economics", "Scientific Computing", "Transcultural Studies"],
    fitFor: ["生命科学", "科研导向", "自然科学", "人文社科研究"],
    application: "研究型项目通常看课程、成绩、研究经历和导师/方向匹配。",
    language: "德语和英语项目并存。",
    materialTips: ["CV 要突出科研和实验方法", "动机信需明确研究兴趣", "推荐信和论文/项目经历很有价值"]
  },
  {
    id: "hu-berlin",
    logo: "/assets/schools/hu-berlin.png",
    rank: "#14",
    name: "柏林洪堡大学",
    englishName: "Humboldt University of Berlin",
    germanName: "Humboldt-Universität zu Berlin",
    city: "Berlin",
    state: "Berlin",
    type: "研究型综合大学",
    website: "https://www.hu-berlin.de/en/studies/counselling/course-catalogue",
    summary: "洪堡大学在人文社科、经济、法律、生命科学和数据交叉方向有较强研究基础。",
    strengths: ["人文社科、经济、法律、生命科学", "柏林学术资源丰富", "适合研究兴趣明确的申请者"],
    programs: ["Economics", "Computer Science", "Social Sciences", "Biology", "Global Studies"],
    fitFor: ["社科研究", "经济学", "生命科学", "柏林目标"],
    application: "项目申请路径和语言要求差异较大，需查看项目页面。",
    language: "德语项目较多，部分英语项目可选。",
    materialTips: ["社科项目要写清方法训练", "德语要求需提前确认", "跨专业需证明课程基础"]
  },
  {
    id: "uni-bonn",
    logo: "/assets/schools/uni-bonn.png",
    rank: "#15",
    name: "波恩大学",
    englishName: "University of Bonn",
    germanName: "Rheinische Friedrich-Wilhelms-Universität Bonn",
    city: "Bonn",
    state: "Nordrhein-Westfalen",
    type: "研究型综合大学",
    website: "https://www.uni-bonn.de/en/studying/degree-programs",
    summary: "波恩大学在数学、经济、农业、生命科学和自然科学方向有较强声誉。",
    strengths: ["数学、经济、生命科学、农业与食品", "研究导向明显", "适合基础学科和量化背景"],
    programs: ["Mathematics", "Economics", "Agricultural Sciences", "Life Science Informatics", "Molecular Biology"],
    fitFor: ["数学经济", "生命科学", "农业食品", "研究路线"],
    application: "项目材料和申请系统按学院不同，需核对官网。",
    language: "德语和英语项目都有。",
    materialTips: ["量化和研究经历很重要", "农业/食品方向要写清专业课程", "动机信避免泛泛而谈"]
  },
  {
    id: "uni-hamburg",
    logo: "/assets/schools/uni-hamburg.png",
    rank: "#16",
    name: "汉堡大学",
    englishName: "University of Hamburg",
    germanName: "Universität Hamburg",
    city: "Hamburg",
    state: "Hamburg",
    type: "大型综合大学",
    website: "https://www.uni-hamburg.de/en/campuscenter/studienangebot.html",
    summary: "汉堡大学覆盖经济、数据、自然科学、气候与环境、人文社科方向，城市资源丰富。",
    strengths: ["经济、数据、气候、环境、自然科学", "港口城市与商业资源", "综合型项目覆盖广"],
    programs: ["Economics", "Data Science", "Climate Physics", "International Business", "Computer Science"],
    fitFor: ["综合申请池", "经济数据", "环境气候", "北德城市偏好"],
    application: "需确认项目是否通过学校系统、uni-assist 或特殊学院流程。",
    language: "德语和英语项目并存。",
    materialTips: ["城市偏好不能替代专业匹配", "气候环境方向要突出数学/自然科学基础", "商科方向重视量化课程"]
  },
  {
    id: "uni-leipzig",
    logo: "/assets/schools/uni-leipzig.png",
    rank: "#17",
    name: "莱比锡大学",
    englishName: "Leipzig University",
    germanName: "Universität Leipzig",
    city: "Leipzig",
    state: "Sachsen",
    type: "综合大学，生活成本友好",
    website: "https://www.uni-leipzig.de/en/studying/prospective-students/courses-of-study",
    summary: "莱比锡大学覆盖人文社科、生命科学、经济、数据和区域研究方向，城市成本相对友好。",
    strengths: ["经济、社会科学、生命科学、区域研究", "生活成本相对可控", "适合作为稳妥或探索候选"],
    programs: ["Economics", "Data Science", "Sustainable Development", "Global Studies", "Biochemistry"],
    fitFor: ["预算敏感", "社科经济", "生命科学", "东德城市偏好"],
    application: "项目要求和语言条件需按官网逐项确认。",
    language: "德语项目较多，也有英语国际项目。",
    materialTips: ["预算理由可以写入选校逻辑", "社科方向要展示研究方法", "生命科学方向要补实验经历"]
  },
  {
    id: "saarland",
    logo: "/assets/schools/saarland.png",
    rank: "#18",
    name: "萨尔大学",
    englishName: "Saarland University",
    germanName: "Universität des Saarlandes",
    city: "Saarbrücken",
    state: "Saarland",
    type: "综合大学，计算机方向突出",
    website: "https://www.uni-saarland.de/en/study/programmes.html",
    summary: "萨尔大学在计算机、语言技术、AI、网络安全和欧洲研究方向具有特色。",
    strengths: ["计算机、AI、语言技术、网络安全", "靠近法国，欧洲化特色明显", "适合计算机方向申请池"],
    programs: ["Computer Science", "Data Science and Artificial Intelligence", "Visual Computing", "Cybersecurity", "Language Science and Technology"],
    fitFor: ["AI/CS", "NLP/语言技术", "网络安全", "跨国区域兴趣"],
    application: "计算机方向项目通常重视算法、数学、编程和项目经历。",
    language: "英语计算机项目较多，也有德语项目。",
    materialTips: ["项目经历要写清技术栈", "算法、数学、系统课程要突出", "NLP 方向可强调语言和数据经验"]
  },
  {
    id: "bielefeld",
    logo: "/assets/schools/bielefeld.png",
    rank: "#19",
    name: "比勒费尔德大学",
    englishName: "Bielefeld University",
    germanName: "Universität Bielefeld",
    city: "Bielefeld",
    state: "Nordrhein-Westfalen",
    type: "综合大学，跨学科研究特色",
    website: "https://www.uni-bielefeld.de/studium/studienangebot/",
    summary: "比勒费尔德大学以社会科学、心理、数据、生命科学和跨学科研究见长，可作为社科数据方向参考。",
    strengths: ["社会科学、心理、数据、生命科学", "跨学科研究氛围", "适合量化社科和心理方向"],
    programs: ["Data Science", "Sociology", "Psychology", "Bioinformatics", "Intelligent Systems"],
    fitFor: ["社会数据", "心理学", "跨学科", "稳妥候选"],
    application: "项目要求需按学院和项目页面核验。",
    language: "德语项目较多，部分英语项目可选。",
    materialTips: ["社科方向要证明统计和方法课程", "心理方向要准备研究方法与实验经历", "跨专业要补课程说明"]
  },
  {
    id: "konstanz",
    logo: "/assets/schools/konstanz.png",
    rank: "#20",
    name: "康斯坦茨大学",
    englishName: "University of Konstanz",
    germanName: "Universität Konstanz",
    city: "Konstanz",
    state: "Baden-Württemberg",
    type: "研究型综合大学，小而精",
    website: "https://www.uni-konstanz.de/en/study/before-you-study/study-programmes/",
    summary: "康斯坦茨大学以研究质量和国际化著称，政治、经济、心理、生命科学和数据方向可关注。",
    strengths: ["政治经济、心理、生命科学、数据", "国际化氛围较好", "适合研究型和小规模校园偏好"],
    programs: ["Social and Economic Data Science", "Politics and Public Administration", "Economics", "Psychology", "Life Science"],
    fitFor: ["社科数据", "公共政策", "经济心理", "小城市偏好"],
    application: "项目数量不如大型大学多，但匹配项目值得认真核对。",
    language: "英语和德语项目都有。",
    materialTips: ["研究兴趣要具体", "社科数据方向重视统计/编程", "动机信可写小规模研究环境匹配"]
  },
  {
    id: "freiburg",
    logo: "/assets/schools/freiburg.png",
    rank: "#21",
    name: "弗赖堡大学",
    englishName: "University of Freiburg",
    germanName: "Albert-Ludwigs-Universität Freiburg",
    city: "Freiburg",
    state: "Baden-Württemberg",
    type: "综合大学，自然科学和可持续方向强",
    website: "https://www.studium.uni-freiburg.de/en/program-offerings",
    summary: "弗赖堡大学在自然科学、环境、森林、可持续、计算和人文社科方向有特色。",
    strengths: ["环境、森林、可持续、自然科学", "南德城市环境好", "研究与应用结合"],
    programs: ["Environmental Sciences", "Forest Sciences", "Renewable Energy", "Computer Science", "Economics"],
    fitFor: ["可持续", "环境森林", "自然科学", "南德偏好"],
    application: "项目要求和申请系统按项目确认。",
    language: "德语项目较多，部分英语硕士项目可选。",
    materialTips: ["可持续方向要突出环境/自然科学课程", "项目经历可写调研、实验或数据分析", "语言要求需提前核对"]
  },
  {
    id: "bremen",
    logo: "/assets/schools/bremen.png",
    rank: "#22",
    name: "不来梅大学",
    englishName: "University of Bremen",
    germanName: "Universität Bremen",
    city: "Bremen",
    state: "Bremen",
    type: "综合大学，海洋、空间与工程特色",
    website: "https://www.uni-bremen.de/en/studies/orientation-application/study-programs",
    summary: "不来梅大学在海洋、空间、工业工程、数据、社会科学和可持续方向有一定特色。",
    strengths: ["空间、海洋、工业工程、数据", "北德城市，生活成本相对友好", "适合扩展申请池"],
    programs: ["Space Engineering", "Marine Geosciences", "Industrial Engineering", "Data Science", "Social Policy"],
    fitFor: ["空间海洋", "工业工程", "预算敏感", "北德偏好"],
    application: "部分项目有较明确的先修课和语言要求。",
    language: "德语和英语项目并存。",
    materialTips: ["空间/海洋方向要准备物理、工程或地学背景", "工业工程需平衡技术与管理课程", "作为探索候选也要核对项目证据"]
  },
  {
    id: "jena",
    logo: "/assets/schools/jena.png",
    rank: "#23",
    name: "耶拿大学",
    englishName: "University of Jena",
    germanName: "Friedrich-Schiller-Universität Jena",
    city: "Jena",
    state: "Thüringen",
    type: "综合大学，生命科学和光学特色",
    website: "https://www.uni-jena.de/en/study-programme",
    summary: "耶拿大学在生命科学、光学、材料、心理、人文社科方向有特色，适合补充中部德国申请池。",
    strengths: ["生命科学、光学、材料、心理", "城市规模适中", "研究氛围较好"],
    programs: ["Molecular Life Sciences", "Photonics", "Materials Science", "Psychology", "Economics"],
    fitFor: ["生命科学", "光学材料", "心理学", "中部德国"],
    application: "按项目核对申请期、语言和材料要求。",
    language: "德语项目较多，也有英语项目。",
    materialTips: ["生命科学和材料方向要突出实验和科研", "光学方向要证明物理/数学基础", "心理方向注意方法和统计课程"]
  },
  {
    id: "hohenheim",
    logo: "/assets/schools/hohenheim.png",
    rank: "#24",
    name: "霍恩海姆大学",
    englishName: "University of Hohenheim",
    germanName: "Universität Hohenheim",
    city: "Stuttgart",
    state: "Baden-Württemberg",
    type: "农业、食品、经济管理特色大学",
    website: "https://www.uni-hohenheim.de/en/study-programmes",
    summary: "霍恩海姆大学在农业、食品科学、营养、经济和管理方向有特色，适合食品、农学、可持续和商科交叉背景。",
    strengths: ["食品科学、农业、营养、可持续经济", "位于斯图加特区域", "适合细分专业精准匹配"],
    programs: ["Food Science and Engineering", "Agricultural Sciences", "Bioeconomy", "International Business and Economics", "Nutritional Science"],
    fitFor: ["食品科学", "农业农经", "可持续经济", "营养方向"],
    application: "具体项目可能有细分先修课要求，需按官网核对。",
    language: "德语和英语项目都有。",
    materialTips: ["食品/农学方向要展示实验、化学、生物和工程课程", "商科交叉要补经济管理基础", "细分方向可作为高精准候选"]
  },
  {
    id: "tu-braunschweig",
    logo: "/assets/schools/tu-braunschweig.png",
    rank: "#25",
    name: "布伦瑞克工业大学",
    englishName: "TU Braunschweig",
    germanName: "Technische Universität Braunschweig",
    city: "Braunschweig",
    state: "Niedersachsen",
    type: "TU9，工程、交通和航空航天特色强",
    website: "https://www.tu-braunschweig.de/en/studies/range-of-courses",
    summary: "布伦瑞克工业大学是 TU9 成员，在机械、交通、航空航天、车辆工程、电子信息和可持续工程方向很有代表性。",
    strengths: ["机械、车辆、航空航天、交通系统", "电子信息、可持续工程、工业工程", "适合作为工科高匹配和中高梯度候选"],
    programs: ["Mechanical Engineering", "Aerospace Engineering", "Automotive Engineering", "Sustainable Engineering", "Electrical Engineering"],
    fitFor: ["机械车辆", "交通航空", "电气信息", "TU9目标"],
    application: "工科项目通常核验先修课、成绩单和语言证明，部分硕士项目要求详细课程匹配。",
    language: "德语项目较多，也有英语或英德混合项目。",
    materialTips: ["机械/车辆方向要突出力学、控制、设计和实验课程", "交通航空方向要避免和汽车方向混排", "项目经历建议写清软件和工程任务"]
  },
  {
    id: "leibniz-hannover",
    logo: "/assets/schools/leibniz-hannover.png",
    rank: "#26",
    name: "汉诺威莱布尼茨大学",
    englishName: "Leibniz University Hannover",
    germanName: "Leibniz Universität Hannover",
    city: "Hannover",
    state: "Niedersachsen",
    type: "TU9，工程与自然科学综合强校",
    website: "https://www.uni-hannover.de/en/studium/studienangebot/",
    summary: "汉诺威莱布尼茨大学在机械、电气、土木、计算、光学、数学和工业工程方向覆盖较广，是工科申请池的重要学校。",
    strengths: ["机械、电气、土木、光学、计算", "生产系统、能源、工业工程", "综合工科覆盖面广"],
    programs: ["Mechanical Engineering", "Electrical Engineering", "Computational Methods", "Optical Technologies", "Water Resources and Environmental Management"],
    fitFor: ["工科基础扎实", "能源环境", "计算工程", "TU9目标"],
    application: "申请路径和语言条件按项目不同，需逐个项目确认先修课和申请截止日期。",
    language: "德语项目较多，也有部分英语项目。",
    materialTips: ["土木/环境项目要突出工程基础和实验实践", "计算工程需强调数学、编程和建模", "动机信需具体到模块和研究方向"]
  },
  {
    id: "tu-dortmund",
    logo: "/assets/schools/tu-dortmund.png",
    rank: "#27",
    name: "多特蒙德工业大学",
    englishName: "TU Dortmund University",
    germanName: "Technische Universität Dortmund",
    city: "Dortmund",
    state: "Nordrhein-Westfalen",
    type: "技术大学，工程、统计、数据和物流特色",
    website: "https://www.tu-dortmund.de/en/studies/",
    summary: "多特蒙德工大在统计、数据、物流、机械、化工、自动化和工业工程方向有特色，适合工程与数据交叉背景。",
    strengths: ["统计、数据、物流、机械、化工", "自动化、工业工程、生产系统", "鲁尔区工业与就业资源"],
    programs: ["Data Science", "Manufacturing Technology", "Automation and Robotics", "Chemical Engineering", "Logistics"],
    fitFor: ["数据统计", "物流工业", "自动化机器人", "鲁尔区偏好"],
    application: "项目通常重视先修课、语言和专业匹配；跨专业申请要证明数学和工程基础。",
    language: "德语和英语项目都有。",
    materialTips: ["数据方向要写清统计、编程和数学课程", "物流工业方向可突出供应链和工程管理经历", "机器人方向要避免被纯机械或纯车辆项目替代"]
  },
  {
    id: "goettingen",
    logo: "/assets/schools/goettingen.png",
    rank: "#28",
    name: "哥廷根大学",
    englishName: "University of Göttingen",
    germanName: "Georg-August-Universität Göttingen",
    city: "Göttingen",
    state: "Niedersachsen",
    type: "研究型综合大学，生命科学、经济和自然科学强",
    website: "https://www.uni-goettingen.de/en/3811.html",
    summary: "哥廷根大学研究传统强，经济、农业、森林、生命科学、数学、物理和数据方向都有较高参考价值。",
    strengths: ["生命科学、农业森林、经济、数学、物理", "研究型项目多", "适合科研和基础学科背景"],
    programs: ["Development Economics", "Applied Statistics", "Molecular Life Sciences", "Forest Sciences", "Sustainable International Agriculture"],
    fitFor: ["经济统计", "生命科学", "农业森林", "研究路线"],
    application: "研究型项目需要认真核对课程背景、语言和项目特定要求。",
    language: "英语硕士项目较多，德语项目也不少。",
    materialTips: ["科研/论文/实验经历要写清", "经济统计方向重视数学和计量课程", "农业森林方向要补充自然科学或可持续经历"]
  },
  {
    id: "muenster",
    logo: "/assets/schools/muenster.png",
    rank: "#29",
    name: "明斯特大学",
    englishName: "University of Münster",
    germanName: "Universität Münster",
    city: "Münster",
    state: "Nordrhein-Westfalen",
    type: "大型综合大学，商科、法律、自然科学和教育强",
    website: "https://www.uni-muenster.de/studium/en/studienangebot/",
    summary: "明斯特大学学科覆盖广，经济、信息系统、化学、物理、生命科学、法律和教育方向均可作为重要候选。",
    strengths: ["商科经济、信息系统、化学、物理", "教育、人文社科、法律", "学生城市氛围强"],
    programs: ["Information Systems", "Business Administration", "Economics", "Chemistry", "Geoinformatics"],
    fitFor: ["商科信息系统", "自然科学", "教育社科", "综合申请池"],
    application: "不同学院申请要求差异明显，需按项目核验语言、先修课和是否限额。",
    language: "德语项目较多，也有英语项目。",
    materialTips: ["信息系统方向需证明商科与计算机双基础", "自然科学项目强调实验和研究经历", "社科教育方向要写清研究兴趣"]
  },
  {
    id: "tuebingen",
    logo: "/assets/schools/tuebingen.png",
    rank: "#30",
    name: "图宾根大学",
    englishName: "University of Tübingen",
    germanName: "Eberhard Karls Universität Tübingen",
    city: "Tübingen",
    state: "Baden-Württemberg",
    type: "研究型综合大学，AI、生命科学、人文社科强",
    website: "https://uni-tuebingen.de/en/study/finding-a-course/degree-programs-available/",
    summary: "图宾根大学在人工智能、机器学习、神经科学、生命科学、医学和人文社科方向很有特色。",
    strengths: ["AI、机器学习、神经科学、生命科学", "医学与认知科学研究氛围强", "适合数据与生命科学交叉背景"],
    programs: ["Machine Learning", "Data Science", "Neuroscience", "Molecular Cell Biology and Immunology", "Computational Linguistics"],
    fitFor: ["AI/机器学习", "神经科学", "生命科学", "计算语言"],
    application: "AI 和生命科学项目竞争强，需核验数学、编程、实验或科研背景。",
    language: "英语硕士较多，德语项目也需要提前确认。",
    materialTips: ["AI 项目要突出数学、算法和项目代码", "生命科学要突出实验方法", "动机信应具体到研究方向和课程模块"]
  },
  {
    id: "wuerzburg",
    logo: "/assets/schools/wuerzburg.png",
    rank: "#31",
    name: "维尔茨堡大学",
    englishName: "University of Würzburg",
    germanName: "Julius-Maximilians-Universität Würzburg",
    city: "Würzburg",
    state: "Bayern",
    type: "综合大学，生命科学、心理、航天信息特色",
    website: "https://www.uni-wuerzburg.de/en/studying-at-jmu/degree-programmes/",
    summary: "维尔茨堡大学在生命科学、心理、医学、卫星技术、航天信息、物理和数据方向有一定特色。",
    strengths: ["生命科学、心理、医学、物理", "卫星技术、航天信息、数据", "巴伐利亚综合型候选"],
    programs: ["Satellite Technology", "Aerospace Information Technology", "Biosciences", "Psychology", "Physics"],
    fitFor: ["生命科学", "心理学", "航天信息", "自然科学"],
    application: "项目要求按学院差异较大，需核对语言、先修课和录取限制。",
    language: "德语和英语项目并存。",
    materialTips: ["航天信息要突出编程、通信、控制或物理基础", "心理生命方向要展示方法和实验经历", "自然科学项目看重课程深度"]
  },
  {
    id: "ulm",
    logo: "/assets/schools/ulm.png",
    rank: "#32",
    name: "乌尔姆大学",
    englishName: "Ulm University",
    germanName: "Universität Ulm",
    city: "Ulm",
    state: "Baden-Württemberg",
    type: "研究型大学，医学、工程、数据和金融数学特色",
    website: "https://www.uni-ulm.de/en/study/study-programmes/",
    summary: "乌尔姆大学在医学、生命科学、数据科学、人工智能、通信、能源和金融数学方向有特色，学校规模相对精干。",
    strengths: ["数据科学、AI、通信、医学工程", "金融数学、能源、生命科学", "南德中小城市环境"],
    programs: ["Cognitive Systems", "Communications Technology", "Energy Science and Technology", "Finance", "Molecular Medicine"],
    fitFor: ["AI认知系统", "通信能源", "金融数学", "医学生命"],
    application: "项目往往要求较清晰的数学、工程或生命科学基础。",
    language: "英语和德语项目都有。",
    materialTips: ["AI/通信方向要突出数学与编程", "金融方向要准备概率统计和金融课程", "医学生命方向需写清实验和科研"]
  },
  {
    id: "duisburg-essen",
    logo: "/assets/schools/duisburg-essen.png",
    rank: "#33",
    name: "杜伊斯堡-埃森大学",
    englishName: "University of Duisburg-Essen",
    germanName: "Universität Duisburg-Essen",
    city: "Duisburg / Essen",
    state: "Nordrhein-Westfalen",
    type: "大型综合大学，工程、经济、教育和医学覆盖广",
    website: "https://www.uni-due.de/en/study_offers.php",
    summary: "杜伊斯堡-埃森大学位于鲁尔区，工程、计算、经济、教育、医学和城市发展方向覆盖较广，适合扩展申请梯度。",
    strengths: ["工程、计算机、经济、教育", "鲁尔区工业和城市研究", "项目覆盖面大"],
    programs: ["Computer Engineering", "Mechanical Engineering", "Economics", "Metallurgy and Metal Forming", "Water Science"],
    fitFor: ["工程计算", "经济教育", "鲁尔区偏好", "稳妥梯度"],
    application: "需按项目核验语言、先修课和申请系统。",
    language: "德语项目较多，也有英语硕士。",
    materialTips: ["工程方向要突出课程完整度", "稳妥梯度也要保证专业证据", "城市/水资源方向可突出实践和项目经历"]
  },
  {
    id: "bochum",
    logo: "/assets/schools/bochum.png",
    rank: "#34",
    name: "波鸿鲁尔大学",
    englishName: "Ruhr University Bochum",
    germanName: "Ruhr-Universität Bochum",
    city: "Bochum",
    state: "Nordrhein-Westfalen",
    type: "大型研究型综合大学，工程、心理、材料和安全方向特色",
    website: "https://studium.ruhr-uni-bochum.de/en/degree-programmes",
    summary: "波鸿鲁尔大学在工程、材料、心理、神经科学、IT 安全和东亚研究等方向有特色，适合鲁尔区申请池。",
    strengths: ["IT安全、材料、机械、心理神经", "鲁尔区高校联盟资源", "综合项目选择多"],
    programs: ["IT Security", "Materials Science", "Mechanical Engineering", "Cognitive Science", "Economics"],
    fitFor: ["IT安全", "材料机械", "心理认知", "鲁尔区偏好"],
    application: "项目要求差异较大，尤其 IT 安全和工程方向要核验先修课。",
    language: "德语和英语项目都有。",
    materialTips: ["IT 安全要突出算法、系统和网络课程", "材料机械要准备实验和设计经历", "心理认知方向需重视方法课程"]
  },
  {
    id: "passau",
    logo: "/assets/schools/passau.png",
    rank: "#35",
    name: "帕绍大学",
    englishName: "University of Passau",
    germanName: "Universität Passau",
    city: "Passau",
    state: "Bayern",
    type: "综合大学，计算机、商科、传媒和国际方向特色",
    website: "https://www.uni-passau.de/en/study/study-options",
    summary: "帕绍大学在计算机、信息系统、商科、国际文化商业、传媒和治理方向有特色，适合跨学科申请。",
    strengths: ["计算机、信息系统、商科、传媒", "国际文化商业、治理与欧洲方向", "小城市环境友好"],
    programs: ["Computer Science", "International Cultural and Business Studies", "Business Administration", "Governance and Public Policy", "Media and Communication"],
    fitFor: ["商科信息系统", "传媒文化", "公共治理", "跨学科"],
    application: "跨学科项目需证明对应课程基础和语言能力。",
    language: "德语项目较多，部分英语项目可选。",
    materialTips: ["商科信息系统要展示双背景", "传媒文化方向要写清实践/作品/研究兴趣", "公共治理方向要重视社科方法"]
  }
];

const CITY_CN = {
  Aachen: "亚琛",
  Berlin: "柏林",
  Bielefeld: "比勒费尔德",
  Bochum: "波鸿",
  Bonn: "波恩",
  Braunschweig: "不伦瑞克",
  Bremen: "不来梅",
  Cologne: "科隆",
  Darmstadt: "达姆施塔特",
  Dortmund: "多特蒙德",
  Dresden: "德累斯顿",
  Duisburg: "杜伊斯堡",
  Erlangen: "埃尔朗根",
  Essen: "埃森",
  Freising: "弗赖辛",
  Freiburg: "弗赖堡",
  Garching: "加兴",
  Göttingen: "哥廷根",
  Hamburg: "汉堡",
  Hannover: "汉诺威",
  Heidelberg: "海德堡",
  Jena: "耶拿",
  Karlsruhe: "卡尔斯鲁厄",
  Konstanz: "康斯坦茨",
  Leipzig: "莱比锡",
  Mannheim: "曼海姆",
  Munich: "慕尼黑",
  Münster: "明斯特",
  Nürnberg: "纽伦堡",
  Passau: "帕绍",
  Saarbrücken: "萨尔布吕肯",
  Stuttgart: "斯图加特",
  Tübingen: "蒂宾根",
  Ulm: "乌尔姆",
  Würzburg: "维尔茨堡"
};

const STATE_CN = {
  "Baden-Württemberg": "巴登-符腾堡州",
  Bayern: "巴伐利亚州",
  Berlin: "柏林州",
  Bremen: "不来梅州",
  Hamburg: "汉堡州",
  Hessen: "黑森州",
  Niedersachsen: "下萨克森州",
  "Nordrhein-Westfalen": "北莱茵-威斯特法伦州",
  Saarland: "萨尔州",
  Sachsen: "萨克森州",
  Thüringen: "图林根州"
};

const TUITION_SOURCES = {
  general: {
    label: "多数连续本科/硕士通常不收取一般学费",
    detail: "通常仍需缴学期费；继续教育、第二学位、长期学习或个别项目可能另收费，最终以学校和项目官网为准。",
    sourceLabel: "德国学生服务机构学费说明",
    sourceUrl: "https://www.studierendenwerke.de/en/topics/student-finance/costs-of-study/tuition-fees"
  },
  badenWuerttemberg: {
    label: "非欧盟学生通常需缴学费",
    detail: "巴登-符腾堡州多数公立高校通常对非欧盟国际学生收取 €1,500/学期；存在法定例外或减免，另有学期费。",
    sourceLabel: "巴登-符腾堡州科学部说明",
    sourceUrl: "https://mwk.baden-wuerttemberg.de/de/hochschulen-studium/studieren-in-bw/studienfinanzierung/gebuehren-fuer-internationale-studierende-und-zweitstudium"
  },
  tum: {
    label: "非欧盟/欧洲经济区新生通常需缴学费",
    detail: "本科通常为 €2,000 或 €3,000/学期，硕士通常为 €4,000 或 €6,000/学期；具体金额按项目页，另有学期费。",
    sourceLabel: "TUM 官方学费说明",
    sourceUrl: "https://www.tum.de/en/studies/fees/tuition"
  }
};

function bilingualPlace(value, translations) {
  const original = String(value || "").trim();
  if (!original) return "";
  const chinese = original
    .split("/")
    .map((part) => translations[part.trim()] || "")
    .filter(Boolean)
    .join(" / ");
  return chinese ? `${original}（${chinese}）` : original;
}

function buildTuition(school) {
  if (school.id === "tum") return TUITION_SOURCES.tum;
  if (school.state === "Baden-Württemberg") return TUITION_SOURCES.badenWuerttemberg;
  return TUITION_SOURCES.general;
}

function buildTags(school) {
  const tags = [];
  if (/TU9/i.test(school.type)) tags.push("TU9精英大学");
  if (/综合/.test(school.type)) tags.push("综合大学");
  if (/商科|经济|管理/.test(`${school.type} ${school.summary}`)) tags.push("商科经济");
  if (/工程|工科|技术|机械|电气|计算机|数据/.test(`${school.type} ${school.summary}`)) tags.push("工程技术");
  if (/生命|医学|食品|农业|环境|可持续/.test(`${school.type} ${school.summary}`)) tags.push("生命与可持续");
  return Array.from(new Set(tags)).slice(0, 4);
}

function buildCategory(school) {
  if (/TU9/i.test(school.type)) return "TU9/工科强校";
  if (/商科|经济|管理/.test(`${school.type} ${school.summary}`)) return "商科经济";
  if (/生命|医学|食品|农业|环境|可持续/.test(`${school.type} ${school.summary}`)) return "生命科学/可持续";
  return "综合大学";
}

function enrichSchool(school) {
  return {
    ...school,
    cityDisplay: bilingualPlace(school.city, CITY_CN),
    stateDisplay: bilingualPlace(school.state, STATE_CN),
    tuition: buildTuition(school),
    category: school.category || buildCategory(school),
    tags: [school.id === "tum" || school.state === "Baden-Württemberg" ? "通常收学费·有例外" : "通常免一般学费·部分项目收费", ...(school.tags || buildTags(school))]
  };
}

function getSchools() {
  return SCHOOLS.map(enrichSchool);
}

function getSchoolById(id) {
  const school = SCHOOLS.find((item) => item.id === id);
  return school ? enrichSchool(school) : null;
}

function getSchoolStats() {
  const schools = getSchools();
  const categories = schools.reduce((acc, school) => {
    acc[school.category] = (acc[school.category] || 0) + 1;
    return acc;
  }, {});
  return {
    total: schools.length,
    categories: Object.entries(categories).map(([name, count]) => ({ name, count }))
  };
}

module.exports = {
  getSchools,
  getSchoolById,
  getSchoolStats
};
